Partially revert "Close test database in all WorkManager tests"
This reverts commit 87ff57593b15e670332861686e5eb30746289685.

Reason for revert: LazyColumn tests started flaking with error "Cannot perform this operation because the connection pool has been closed.
java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed."

Change-Id: Ib2f4dac3ce579cc96de69fda59c104590e6ef02c