Fix failing desktop tests (#1770)
1. Fix flaky tests because of
[GlobalSnapshotManager](https://youtrack.jetbrains.com/issue/CMP-7374/Execution-of-ComposeScenes-in-other-threads-is-affected-by-GlobalSnapshotManager-in-main-thread):
```
Expected :Exit
Actual   :Move
<Click to see difference>

java.lang.AssertionError: expected:<Exit> but was:<Move>
	at androidx.compose.ui.AssertKt.isEqualTo(Assert.kt:26)
	at androidx.compose.ui.EventTestUtilsKt.assertHas-PfEQiPw(EventTestUtils.kt:65)
	at androidx.compose.ui.EventTestUtilsKt.assertReceivedLast-PfEQiPw(EventTestUtils.kt:58)
	at androidx.compose.ui.ComposeSceneInputTest.move to popup(ComposeSceneInputTest.kt:92)
```

2. Fix failing window desktop tests if density = 1.5:
```
expected: 351 x 517
but was : 351 x 518
Expected :351 x 517
Actual   :351 x 518
<Click to see difference>

expected: 351 x 517
but was : 351 x 518
	at androidx.compose.ui.awt.ComposeWindowTest$don't override user preferred size$1.invokeSuspend(ComposeWindowTest.kt:158)
```