Fix NoSuchMethodError
We update to use ActivityStack.Token to replace raw IBinder usage
in vendor API level 5. It leads to some app crashes with
NoSuchMethodError because they use previous level 5 build
of Window Jetpack library.

Instead of changing the #getToken signature, this CL deprecates
getToken with IBinder and use #getActivityStackToken to return
ActivityStack.Token.

Test: presubmit
Bug: 329997430
Relnote: Deprecate #getToken and add #getActivityStackToken
Change-Id: Ie047116259409389ae6c544929f50a6a8114774a