Fix invalid deeplink regex syntax (#1286)
From
[docs](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/-regex/):
> For JS
>
> Note that RegExp objects under the hood are constructed with [the "u"
flag](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode)
that enables Unicode-related features in regular expressions. This also
makes the pattern syntax more strict, for example, prohibiting
unnecessary escape sequences.

JS has stricter regex validation rules, so copied from android regexes
doesn't work.

```
Invalid regular expression: /(\?|\#|$)/gu: Invalid escape
SyntaxError: Invalid regular expression: /(\?|\#|$)/gu: Invalid escape
SyntaxError: Invalid regular expression: /^multiplatform-app://androidx\.navigation/ConfigurablePopup($|(\?(.)*)|(\#(.)*))/giu: Invalid escape
```

IDEA also thinks that it's "redundant"

<img width="524" alt="image"
src="https://github.com/JetBrains/compose-multiplatform-core/assets/1836384/ca91e003-4a77-4777-9287-ba4a32806943">


## Testing

Test: run mpp on JS target

## Issues Fixed

Fixes regression after
https://github.com/JetBrains/compose-multiplatform-core/pull/1277