Add commit hook for checking IDEA-specific suppress comments that cause warnings at compile time.
Test: Manually tested repo upload-ing a CL with touching a file with one illegal suppress, and adding another. Sample output below:

ccraik@ccraik840:/media/ccraik/google4/androidx-master-dev/frameworks/support$ ru
[COMMIT daba9c34d3c1] testcommit
[FAILED] invalid_suppress_hook
    Invalid, IDEA-specific warning suppression found. This causes warnings with command line compilation.

    /media/ccraik/google4/androidx-master-dev/frameworks/support/paging/runtime/src/main/java/androidx/paging/LivePagedList.java:102:
    Error: unsupported comment suppression
            //noinspection unchecked
            return PagedList.create(
                    dataSource,
    Instead, please use: @SuppressWarnings("unchecked")

    /media/ccraik/google4/androidx-master-dev/frameworks/support/paging/rxjava2/src/main/java/androidx/paging/RxPagedListBuilder.java:330:
    Error: unsupported comment suppression
                    //noinspection deprecation
                    mList = new PagedList.Builder<>(mDataSource, mConfig)
                            .setNotifyExecutor(mNotifyExecutor)
    Instead, please use: @SuppressWarnings("deprecation")

[FAILED] repohooks for platform/frameworks/support failed

Change-Id: I001a7b2d119e5f7d889363d329583c345cb16c95